In [274]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import pylab as plt
import seaborn as sns
pd.set_option('display.max_columns', None)
import re
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

#%matplotlib inline

In [223]:
train = pd.read_csv(r'train.csv')
test = pd.read_csv(r'test.csv')
sample = pd.read_csv(r'muestra.csv')

In [224]:
junto = pd.concat([train,test], axis=0)

In [225]:
categorias = pd.get_dummies(junto["Category"])

In [226]:
categorias.columns

Index(['2 in 1 Convertible', 'Gaming', 'Netbook', 'Notebook', 'Ultrabook',
       'Workstation'],
      dtype='object')

In [227]:
junto.columns

Index(['Manufacturer', 'Model Name', 'Category', 'Screen Size', 'Screen',
       'CPU', 'RAM', ' Storage', 'GPU', 'Operating System',
       'Operating System Version', 'Weight', 'Price'],
      dtype='object')

In [228]:
fabricante = pd.get_dummies(junto['Manufacturer'])

In [229]:
fabricante.columns

Index(['Acer', 'Apple', 'Asus', 'Chuwi', 'Dell', 'Fujitsu', 'Google', 'HP',
       'Huawei', 'LG', 'Lenovo', 'MSI', 'Mediacom', 'Microsoft', 'Razer',
       'Samsung', 'Toshiba', 'Vero', 'Xiaomi'],
      dtype='object')

In [230]:
junto = junto.drop("Model Name", axis=1)

In [231]:
junto.columns

Index(['Manufacturer', 'Category', 'Screen Size', 'Screen', 'CPU', 'RAM',
       ' Storage', 'GPU', 'Operating System', 'Operating System Version',
       'Weight', 'Price'],
      dtype='object')

In [232]:
junto.head(2)

Manufacturer   Category Screen Size                              Screen  \
0        Apple  Ultrabook       13.3"  IPS Panel Retina Display 2560x1600   
1        Apple  Ultrabook       13.3"                            1440x900   

                    CPU  RAM              Storage  \
0  Intel Core i5 2.3GHz  8GB            128GB SSD   
1  Intel Core i5 1.8GHz  8GB  128GB Flash Storage   

                            GPU Operating System Operating System Version  \
0  Intel Iris Plus Graphics 640            macOS                      NaN   
1        Intel HD Graphics 6000            macOS                      NaN   

   Weight        Price  
0  1.37kg  11912523.48  
1  1.34kg   7993374.48

In [233]:
junto["GPU"].unique()

array(['Intel Iris Plus Graphics 640', 'Intel HD Graphics 6000',
       'Intel HD Graphics 620', 'AMD Radeon Pro 455',
       'Intel Iris Plus Graphics 650', 'AMD Radeon R5',
       'Intel Iris Pro Graphics', 'Nvidia GeForce MX150',
       'Intel UHD Graphics 620', 'Intel HD Graphics 520',
       'AMD Radeon Pro 555', 'AMD Radeon R5 M430',
       'Intel HD Graphics 615', 'AMD Radeon Pro 560',
       'Nvidia GeForce 940MX', 'Intel HD Graphics 400',
       'Nvidia GeForce GTX 1050', 'AMD Radeon R2', 'AMD Radeon 530',
       'Nvidia GeForce 930MX', 'Intel HD Graphics',
       'Intel HD Graphics 500', 'Nvidia GeForce 930MX ',
       'Nvidia GeForce GTX 1060', 'Nvidia GeForce 150MX',
       'Intel Iris Graphics 540', 'AMD Radeon RX 580',
       'Nvidia GeForce 920MX', 'AMD Radeon R4 Graphics', 'AMD Radeon 520',
       'Nvidia GeForce GTX 1070', 'Nvidia GeForce GTX 1050 Ti',
       'Nvidia GeForce MX130', 'AMD R4 Graphics',
       'Nvidia GeForce GTX 940MX', 'AMD Radeon RX 560',
       'Nvid

In [234]:
junto = junto.drop("GPU", axis=1)

In [235]:
junto["Operating System"].unique()

array(['macOS', 'No OS', 'Windows', 'Mac OS', 'Linux', 'Android',
       'Chrome OS'], dtype=object)

In [236]:
sistema_operativo = pd.get_dummies(junto["Operating System"])

In [237]:
junto.fillna(0, inplace = True)

In [238]:
junto["Screen"].unique()

array(['IPS Panel Retina Display 2560x1600', '1440x900',
       'Full HD 1920x1080', 'IPS Panel Retina Display 2880x1800',
       '1366x768', 'IPS Panel Full HD 1920x1080',
       'IPS Panel Retina Display 2304x1440',
       'IPS Panel Full HD / Touchscreen 1920x1080',
       'Full HD / Touchscreen 1920x1080',
       'Touchscreen / Quad HD+ 3200x1800',
       'IPS Panel Touchscreen 1920x1200', 'Touchscreen 2256x1504',
       'Quad HD+ / Touchscreen 3200x1800', 'IPS Panel 1366x768',
       'IPS Panel 4K Ultra HD / Touchscreen 3840x2160',
       'IPS Panel Full HD 2160x1440',
       '4K Ultra HD / Touchscreen 3840x2160', 'Touchscreen 2560x1440',
       '1600x900', 'IPS Panel 4K Ultra HD 3840x2160',
       '4K Ultra HD 3840x2160', 'Touchscreen 1366x768',
       'IPS Panel Full HD 1366x768', 'IPS Panel 2560x1440',
       'IPS Panel Full HD 2560x1440',
       'IPS Panel Retina Display 2736x1824', 'Touchscreen 2400x1600',
       '2560x1440', 'IPS Panel Quad HD+ 2560x1440',
       'IPS Panel 

In [239]:
junto = junto.drop("Screen", axis=1)

In [240]:
junto = junto.drop('Manufacturer', axis=1)
junto = junto.drop('Category', axis=1)
junto = junto.drop('Operating System', axis=1)

In [241]:
junto["RAM"].unique()

array(['8GB', '16GB', '4GB', '2GB', '12GB', '6GB', '32GB', '24GB', '64GB'],
      dtype=object)

In [242]:
junto['RAM'] = junto['RAM'].str.replace(r'\D', '', regex=True)

In [243]:
junto['RAM'] = junto['RAM'].astype(int)

In [244]:
junto = junto.rename(columns={'RAM': 'RAM(GB)'})

In [245]:
junto["RAM(GB)"].unique()

array([ 8, 16,  4,  2, 12,  6, 32, 24, 64])

In [246]:
junto = junto.rename(columns={' Storage': 'Storage'})

In [247]:
junto["Screen Size"].unique()

array(['13.3"', '15.6"', '15.4"', '14.0"', '12.0"', '11.6"', '17.3"',
       '10.1"', '13.5"', '12.5"', '13.0"', '18.4"', '13.9"', '12.3"',
       '17.0"', '15.0"', '14.1"', '11.3"'], dtype=object)

In [248]:
junto['Screen Size'] = junto['Screen Size'].str.replace('"', '')

In [249]:
junto['Screen Size'] = junto['Screen Size'].astype(float)

In [250]:
junto["Screen Size"].unique()

array([13.3, 15.6, 15.4, 14. , 12. , 11.6, 17.3, 10.1, 13.5, 12.5, 13. ,
       18.4, 13.9, 12.3, 17. , 15. , 14.1, 11.3])

In [251]:
junto.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1302 entries, 0 to 324
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Screen Size               1302 non-null   float64
 1   CPU                       1302 non-null   object 
 2   RAM(GB)                   1302 non-null   int32  
 3   Storage                   1302 non-null   object 
 4   Operating System Version  1302 non-null   object 
 5   Weight                    1302 non-null   object 
 6   Price                     1302 non-null   float64
dtypes: float64(2), int32(1), object(4)
memory usage: 76.3+ KB


In [252]:
junto["CPU"].unique()

array(['Intel Core i5 2.3GHz', 'Intel Core i5 1.8GHz',
       'Intel Core i5 7200U 2.5GHz', 'Intel Core i7 2.7GHz',
       'Intel Core i5 3.1GHz', 'AMD A9-Series 9420 3GHz',
       'Intel Core i7 2.2GHz', 'Intel Core i7 8550U 1.8GHz',
       'Intel Core i5 8250U 1.6GHz', 'Intel Core i3 6006U 2GHz',
       'Intel Core i7 2.8GHz', 'Intel Core M m3 1.2GHz',
       'Intel Core i7 7500U 2.7GHz', 'Intel Core i7 2.9GHz',
       'Intel Core i3 7100U 2.4GHz', 'Intel Atom x5-Z8350 1.44GHz',
       'Intel Core i5 7300HQ 2.5GHz', 'AMD E-Series E2-9000e 1.5GHz',
       'Intel Core i5 1.6GHz', 'Intel Core i7 8650U 1.9GHz',
       'Intel Atom x5-Z8300 1.44GHz', 'AMD E-Series E2-6110 1.5GHz',
       'AMD A6-Series 9220 2.5GHz',
       'Intel Celeron Dual Core N3350 1.1GHz',
       'Intel Core i3 7130U 2.7GHz', 'Intel Core i7 7700HQ 2.8GHz',
       'Intel Core i5 2.0GHz', 'AMD Ryzen 1700 3GHz',
       'Intel Pentium Quad Core N4200 1.1GHz',
       'Intel Atom x5-Z8550 1.44GHz',
       'Intel Celeron Du

In [253]:
cpu = pd.get_dummies(junto["CPU"])

In [254]:
junto = junto.drop('CPU', axis=1)

In [255]:
junto["Storage"].unique()

array(['128GB SSD', '128GB Flash Storage', '256GB SSD', '512GB SSD',
       '500GB HDD', '256GB Flash Storage', '1TB HDD',
       '32GB Flash Storage', '128GB SSD +  1TB HDD',
       '256GB SSD +  256GB SSD', '64GB Flash Storage',
       '256GB SSD +  1TB HDD', '256GB SSD +  2TB HDD', '32GB SSD',
       '2TB HDD', '64GB SSD', '1TB Hybrid', '512GB SSD +  1TB HDD',
       '1TB SSD', '256GB SSD +  500GB HDD', '128GB SSD +  2TB HDD',
       '512GB SSD +  512GB SSD', '16GB SSD', '16GB Flash Storage',
       '512GB SSD +  256GB SSD', '512GB SSD +  2TB HDD',
       '64GB Flash Storage +  1TB HDD', '1GB SSD', '1TB HDD +  1TB HDD',
       '32GB HDD', '1TB SSD +  1TB HDD', '512GB Flash Storage',
       '128GB HDD', '240GB SSD', '8GB SSD', '508GB Hybrid',
       '512GB SSD +  1TB Hybrid', '256GB SSD +  1TB Hybrid'], dtype=object)

In [256]:
junto = junto.rename(columns={' Storage': 'Storage'})
pattern_storage = r'(\d+)(TB|GB)'
    
def convert_storage(storage):
    match = re.match(pattern_storage, storage)
    if match:
        size = int(match.group(1))
        unit = match.group(2)
        if unit == 'TB':
            size *= 1024
        return size
    return None


In [257]:
junto['Storage'] = junto['Storage'].apply(convert_storage)

In [258]:
junto["Storage"].unique()

array([ 128,  256,  512,  500, 1024,   32,   64, 2048,   16,    1,  240,
          8,  508], dtype=int64)

In [259]:
junto["Operating System Version"].unique()

array([0, '10', 'X', '10 S', '7'], dtype=object)

In [260]:
junto = junto.drop(columns=['Operating System Version'])

In [261]:
junto["Weight"].unique()

array(['1.37kg', '1.34kg', '1.86kg', '1.83kg', '2.1kg', '2.04kg', '1.3kg',
       '1.6kg', '2.2kg', '0.92kg', '1.22kg', '0.98kg', '2.5kg', '1.62kg',
       '1.91kg', '2.3kg', '1.35kg', '1.88kg', '1.89kg', '1.65kg',
       '2.71kg', '1.2kg', '1.44kg', '2.8kg', '2kg', '2.65kg', '2.77kg',
       '3.2kg', '0.69kg', '1.49kg', '2.4kg', '2.13kg', '2.43kg', '1.7kg',
       '1.4kg', '1.8kg', '1.9kg', '3kg', '1.252kg', '2.7kg', '2.02kg',
       '1.63kg', '1.96kg', '1.21kg', '2.45kg', '1.25kg', '1.5kg',
       '2.62kg', '1.38kg', '1.58kg', '1.85kg', '1.23kg', '1.26kg',
       '2.16kg', '2.36kg', '2.05kg', '1.32kg', '1.75kg', '0.97kg',
       '2.9kg', '2.56kg', '1.48kg', '1.74kg', '1.1kg', '1.56kg', '2.03kg',
       '1.05kg', '4.4kg', '1.90kg', '1.29kg', '2.0kg', '1.95kg', '2.06kg',
       '1.12kg', '1.42kg', '3.49kg', '3.35kg', '2.23kg', '4.42kg',
       '2.69kg', '2.37kg', '4.7kg', '3.6kg', '2.08kg', '4.3kg', '1.68kg',
       '1.41kg', '4.14kg', '2.18kg', '2.24kg', '2.67kg', '2.14kg',
       '1.

In [262]:
junto = junto.drop(columns=['Weight'])

In [263]:
junto.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1302 entries, 0 to 324
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Screen Size  1302 non-null   float64
 1   RAM(GB)      1302 non-null   int32  
 2   Storage      1302 non-null   int64  
 3   Price        1302 non-null   float64
dtypes: float64(2), int32(1), int64(1)
memory usage: 45.8 KB


In [264]:
junto = pd.concat([junto, fabricante,categorias,sistema_operativo, cpu], axis=1)

In [266]:
new_test = junto.tail(325)
new_train = junto.head(977)

In [267]:
junto.head()

Screen Size  RAM(GB)  Storage        Price  Acer  Apple  Asus  Chuwi  Dell  \
0         13.3        8      128  11912523.48     0      1     0      0     0   
1         13.3        8      128   7993374.48     0      1     0      0     0   
2         15.6        8      256   5112900.00     0      0     0      0     0   
3         15.4       16      512  22563005.40     0      1     0      0     0   
4         13.3        8      256  16037611.20     0      1     0      0     0   

   Fujitsu  Google  HP  Huawei  LG  Lenovo  MSI  Mediacom  Microsoft  Razer  \
0        0       0   0       0   0       0    0         0          0      0   
1        0       0   0       0   0       0    0         0          0      0   
2        0       0   1       0   0       0    0         0          0      0   
3        0       0   0       0   0       0    0         0          0      0   
4        0       0   0       0   0       0    0         0          0      0   

   Samsung  Toshiba  Vero  Xiaomi  2 in 1 Convertible  Gaming  Netbook  \
0        0        0     0       0                   0       0        0   
1        0        0     0       0                   0       0        0   
2        0        0     0       0                   0       0        0   
3        0        0     0       0                   0       0        0   
4        0        0     0       0                   0       0        0   

   Notebook  Ultrabook  Workstation  Android  Chrome OS  Linux  Mac OS  No OS  \
0         0          1            0        0          0      0       0      0   
1         0          1            0        0          0      0       0      0   
2         1          0            0        0          0      0       0      1   
3         0          1            0        0          0      0       0      0   
4         0          1            0        0          0      0       0      0   

   Windows  macOS  AMD A10-Series 9600P 2.4GHz  AMD A10-Series 9620P 2.5GHz  \
0        0      1                            0                            0   
1        0      1                            0                            0   
2        0      0                            0                            0   
3        0      1                            0                            0   
4        0      1                            0                            0   

   AMD A10-Series A10-9620P 2.5GHz  AMD A12-Series 9700P 2.5GHz  \
0                                0                            0   
1                                0                            0   
2                                0                            0   
3                                0                            0   
4                                0                            0   

   AMD A12-Series 9720P 2.7GHz  AMD A12-Series 9720P 3.6GHz  \
0                            0                            0   
1                            0                            0   
2                            0                            0   
3                            0                            0   
4                            0                            0   

   AMD A4-Series 7210 2.2GHz  AMD A6-Series 7310 2GHz  \
0                          0                        0   
1                          0                        0   
2                          0                        0   
3                          0                        0   
4                          0                        0   

   AMD A6-Series 9220 2.5GHz  AMD A6-Series 9220 2.9GHz  \
0                          0                          0   
1                          0                          0   
2                          0                          0   
3                          0                          0   
4                          0                          0   

   AMD A6-Series A6-9220 2.5GHz  AMD A8-Series 7410 2.2GHz  \
0                             0                          0   
1                             

PARTE 2

In [273]:
# Dividir los datos en características (X) y etiquetas (y)
X = new_train.drop('Price', axis=1) 
y = new_train['Price']

# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = tts(X, y, test_size=0.2, random_state=42)

# Calcular MSE para cada modelo
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)
linear_pred = linear_model.predict(X_test)
linear_mse = mean_squared_error(y_test, linear_pred)


tree_model = DecisionTreeRegressor()
tree_model.fit(X_train, y_train)
tree_pred = tree_model.predict(X_test)
tree_mse = mean_squared_error(y_test, tree_pred)


forest_model = RandomForestRegressor()
forest_model.fit(X_train, y_train)
forest_pred = forest_model.predict(X_test)
forest_mse = mean_squared_error(y_test, forest_pred)

In [275]:
# Calcular r cuadrado para cada modelo

linear_r2 = r2_score(y_test, linear_pred)

tree_r2 = r2_score(y_test, tree_pred)

forest_r2 = r2_score(y_test, forest_pred)

In [276]:
print('Linear Regression: MSE->',linear_mse,'  R cuadrado->',linear_r2)
print('Decision Tree:     MSE->',tree_mse,'      R cuadrado->',tree_r2)
print('Random Forest:     MSE->',forest_mse,'       R cuadrado->',forest_r2)

Linear Regression: MSE-> 2.8604531330499545e+26   R cuadrado-> -7911592863351.874
Decision Tree:     MSE-> 12190042960500.336       R cuadrado-> 0.6628413317598126
Random Forest:     MSE-> 8685648863677.695        R cuadrado-> 0.7597677208219394


In [278]:
X = new_test.drop(['Price'], axis = 1)
y = new_test['Price']

In [279]:
prediction_randomforest = forest_model.predict(X)

In [280]:
new_test['Price'] = prediction_randomforest

In [281]:
new_test['id'] = range (0, len(new_test))

In [282]:
new_test.columns

Index(['Screen Size', 'RAM(GB)', 'Storage', 'Price', 'Acer', 'Apple', 'Asus',
       'Chuwi', 'Dell', 'Fujitsu',
       ...
       'Intel Pentium Dual Core 4405Y 1.5GHz',
       'Intel Pentium Dual Core N4200 1.1GHz',
       'Intel Pentium Quad Core N3700 1.6GHz',
       'Intel Pentium Quad Core N3710 1.6GHz',
       'Intel Pentium Quad Core N4200 1.1GHz', 'Intel Xeon E3-1505M V6 3GHz',
       'Intel Xeon E3-1535M v5 2.9GHz', 'Intel Xeon E3-1535M v6 3.1GHz',
       'Samsung Cortex A72&A53 2.0GHz', 'id'],
      dtype='object', length=155)

In [283]:
solution = new_test[['id', 'Price']]

In [284]:
solution.reset_index(drop = True, inplace = True)
solution

id         Price
0      0  6.556608e+06
1      1  1.577964e+07
2      2  1.434227e+07
3      3  8.375138e+06
4      4  3.590086e+06
..   ...           ...
320  320  5.055216e+06
321  321  1.677205e+07
322  322  2.595536e+06
323  323  3.782460e+06
324  324  3.467534e+06

[325 rows x 2 columns]

In [287]:
solution.to_csv('solution.csv', index = False)
solution

id         Price
0      0  6.556608e+06
1      1  1.577964e+07
2      2  1.434227e+07
3      3  8.375138e+06
4      4  3.590086e+06
..   ...           ...
320  320  5.055216e+06
321  321  1.677205e+07
322  322  2.595536e+06
323  323  3.782460e+06
324  324  3.467534e+06

[325 rows x 2 columns]